# Generated by Django 3.1.1 on 2020-10-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auctions',
            new_name='Auction',
        ),
    ]
